

spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/juma
      username: postgres
      password: juma1999


  jpa:
  hibernate:
      ddl-auto: none
      show-sql: true
      properties: hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      format_sql: true







