
app:
  spring:
  datasource:
      main:
         driver-class-name: org.postgresql.Driver
         jdbc-url: jdbc:postgresql://localhost:5432/backend
         username: postgres
         password: juma1999
         pool-size: 30




server:
   error:
    include-binding-error: always
    include-message: always
