

spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/simpleproject
      username: postgres
      password: juma1999

  jpa:
  hibernate:
      ddl-auto: update
      show-sql: true
      properties: hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      format_sql: true






